# Generated by Django 4.2.24 on 2025-09-17 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', '-jornada'],
                'unique_together': {('jornada', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('number', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('first_name', 'last_name', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PescaraGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Loss')], max_length=1)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_vs_pescara', to='stats.team')),
                ('players', models.ManyToManyField(related_name='games', through='stats.Appearance', to='stats.player')),
            ],
            options={
                'ordering': ['date', 'jornada'],
            },
        ),
        migrations.CreateModel(
            name='LeagueTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('played', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stats.leaguetable')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.team')),
            ],
            options={
                'ordering': ['table', 'position'],
            },
        ),
        migrations.AddField(
            model_name='appearance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='stats.pescaragame'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='stats.player'),
        ),
        migrations.AddIndex(
            model_name='pescaragame',
            index=models.Index(fields=['jornada'], name='stats_pesca_jornada_7b7aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='pescaragame',
            index=models.Index(fields=['date'], name='stats_pesca_date_7d50bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pescaragame',
            unique_together={('jornada', 'opponent')},
        ),
        migrations.AlterUniqueTogether(
            name='leaguetableentry',
            unique_together={('table', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='appearance',
            unique_together={('game', 'player')},
        ),
    ]
