# Generated by Django 4.2.24 on 2025-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetableentry',
            name='draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguetableentry',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguetableentry',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
