# Generated by Django 4.2.24 on 2025-09-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_leaguetableentry_draws_leaguetableentry_losses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Pescara', max_length=120)),
                ('league_name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('color_primary', models.CharField(blank=True, default='', max_length=7)),
                ('color_accent', models.CharField(blank=True, default='', max_length=7)),
                ('color_win', models.CharField(blank=True, default='', max_length=7)),
                ('color_draw', models.CharField(blank=True, default='', max_length=7)),
                ('color_loss', models.CharField(blank=True, default='', max_length=7)),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_home_club', to='stats.team')),
            ],
        ),
    ]
