# Generated by Django 4.2.24 on 2025-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_rounds',
            field=models.PositiveSmallIntegerField(default=25, help_text='Total de jornadas.'),
        ),
    ]
